# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-17 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_address', models.CharField(max_length=250)),
            ],
        ),
    ]
