# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180917_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'emp_profile',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Employee'),
        ),
    ]
